name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd frontend-en
        npm install

    - name: Build
      run: |
        cd frontend-en
        npm run build
      env:
        CI: false
        REACT_APP_CONTRACT_ADDRESS: ${{ secrets.REACT_APP_CONTRACT_ADDRESS }}
        REACT_APP_TOKEN_ADDRESS: ${{ secrets.REACT_APP_TOKEN_ADDRESS }}

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./frontend-en/build

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
